name: flutter_getx
description: Projeto em flutter utilizando a biblioteca GetX para gerenciamento de estado.

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get: ^3.16.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

